name: CI

on: pull_request

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v4

      - name: Install X11 libraries
        run: sudo apt-get install libx11-dev libxft-dev

      - name: Compile st
        run: make

  terminfo:
    name: Terminfo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v4

      - name: Compile st's terminfo entry
        run: tic -sx st.info
